### ISSUE TITLE
Rails 7 compatibility

### ISSUE THREAD

**Issue by PatrickMcSweeny** [mbulat/plutus#146]
I am attempting to upgrade an existing application to Rails 7, and when I attempt to start rails server in my terminal I get the following error:

gems/plutus-0.17/app/controllers/plutus/entries_controller.rb:14:in `<class:EntriesController>': undefined local variable or method `unloadable' for Plutus::EntriesController:Class (NameError)

I did some digging in the activesupport source files, and it looks like the 'unloadable' method has been removed in the 7.0 branch.

**Comment by kirantpatil** [comment]
Hi @PatrickMcSweeny 
How is it going on Rails 7?
Are you using it on production ?

**Comment by kirantpatil** [comment]
Hi @mbulat 
Any updates on supporting Rails 7 ?

**Comment by mbulat** [comment]
I had given it a try when 7.0 came out, but a lot of gem dependencies at the time had issues. I might try again assuming gems have had time to update when I get a chance. 

If anyone wants to give it a shot, feel free to send in a pull request.

**Comment by mbulat** [comment]
Awesome, many thanks! Rails 7 updates merged. Anyone with any issues, please post back.

**Comment by kirantpatil** [comment]
Hi @mbulat,

How to update the gem in application ?

Will you release new version ?

Thanks.

**Comment by mbulat** [comment]
At the moment, master branch is supporting Rails 7 so you can use the git path in the Gemfile. 

Usually I give things a little while to make sure there are no outstanding problems and then I'll bump the version number and publish a new gem once it's fairly stable.

**Comment by moseslucas** [comment]
Problem still persisting.
```
/Users/mo/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/plutus-0.17/app/controllers/plutus/accounts_controller.rb:14:in `<class:AccountsController>': undefined local variable or method `unloadable' for Plutus::AccountsController:Class (NameError)

```
Rails Version 7.0
Ruby 3.1.2
Plutus 0.17

**Comment by amit** [comment]
Try using the git version of the gem. Unfortunately, the owner/maintainer of the gem is not releasing a new version of this gem!

**Comment by mbulat** [comment]
Hi all! Sorry for the delays, I'll try and get to this today and get a release out.

**Comment by crifat** [comment]
Any plan to release?

**Comment by khaled-badenjki** [comment]
any plans to release? @mbulat

**Comment by mbulat** [comment]
Better late than never!  :blush:  Pushed 0.18 for Rails 7 support
